
CHCP 65001
@echo off
cls
echo [Downloading packages...]
echo[
call npm install > /dev/null
echo [Packages Installed]
echo[
echo [Building code...]
echo[
call tsc
echo[
echo [Code compiled]
cls
echo ╔═════════════════════════════════════════════════════════════╗
echo ║                    Welcome to MapleNode!                    ║
echo ╔═════════════════════════════════════════════════════════════╗
echo ║ WWWWWWWWWWWWWWWWWWWWWWW@=#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW ║
echo ║ WWWWWWWWWWWWWWWWWWWWWW#====@WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW ║
echo ║ WWWWWWWWWWWWWWWWWWWWWWW#==#===#WWWWWWWWWWWWWWWWWWWWWWWWWWWW ║
echo ║ WWWWWWWWWWWWWWWWWWWWWWWW=#WWW@#==#WWWWWWWWWWWWWWWWWWWWWWWWW ║
echo ║ WWWWWWWWWWWWWWWWWWWWWWWW==WWWWWW@#=#WWWWWWWWWWWWWWWWWWWWWWW ║
echo ║ WWWWWWWWWWWWWWWWWWWWWWWW#=@WWWWWWW@===#WWWWWWWWWWWWWWWWWWWW ║
echo ║ WWWWWWWWWWWWWWWWWWWWWWWWW==WWWWWWWW====WWWWWWWWWWWWWWWWWWWW ║
echo ║ WWWWWW#============#@W@@WW==WWWWWWWWW@=#WWWWWWWW@#@WWWWWWWW ║
echo ║ WWWWWW#===@WWWWWWWW@=====WW==#WWWWWWWW@=@WWWWWW#===#WWWWWWW ║
echo ║ WWWWWWWWW==@WWWWWWWWW#==@WWW@=====WWWWW#=WWWWWW#=##WWWWWWWW ║
echo ║ WWWWWWWWWW#==@WWWWWWWWWWWWWWWW====WWWWW@=#WWW#=#WWWWWWWWWWW ║
echo ║ WWWWWWWWWWWW#==#WWWWWWWWWWWWWWWWWWWWWWW#=====@WWWWWWWWWWWWW ║
echo ║ WWWWWWWWWWWWWW@#==#@@WWWWWWWW@@#=====###===#WWWWWWWWWWWWWWW ║
echo ║ WWWWWWWWWWWWWWWWWW@##========#@WWWWWWWWW@=##=@WWWWWWWWWWWWW ║
echo ║ WWWWWWWWWWWWWWWWWWW@#======@WWWWWWWWWWWW@=#W@==@WWWWWWWWWWW ║
echo ║ WWWWWWWWWWWWWWWW@===#WWWWWWWWWWWWWWWWWWWW=#WWW@=#WWWWWWWWWW ║
echo ║ WWWWWWWWWWWWW@===@WWWWWWWWWWWWWWWWWWWWWWW=#WWWWW#=#@WWWWWWW ║
echo ║ WWWWWWWWWW@===@WWWWWWWWWWWWWW@===#WWWWWW@=@WWWWW#===#WWWWWW ║
echo ║ WWWWWWW====#WWWWWWWWWW====@WW#====WWWWW#===@WWWWW#=@WWWWWWW ║
echo ║ WWWWWWW===================WWW#=@WWWWWWW#===@WWWWWW##WWWWWWW ║
echo ║ WWWWWWWWWWWWWWWWWWWWWWWWWWWW@=#WWWWWWWW#=@WWWWWWWW@=@WWWWWW ║
echo ║ WWWWWWWWWWWWWWWWWWWWWWWWWWWW==WWWWWWWW@=#WW@===WWW@=@WWWWWW ║
echo ║ WWWWWWWWWWWWWWWWWWWWWWWWWWW==WWWWWWWW@=#WWW====#WWW=@WWWWWW ║
echo ║ WWWWWWWWWWWWWWWWWWWWWWWWWW@=#WWWWWWW@=#WWWWW@#==WW@=@WWWWWW ║
echo ║ WWWWWWWWWWWWWWWWWWWWWWWWWW==WWWWWWW#=#WWWWWWWWW#==#=#WWWWWW ║
echo ║ WWWWWWWWWWWWWWWWWWWWWWWWW@=#WWWWW@==@WWWWWWWWWWWW#====WWWWW ║
echo ║ WWWWWWWWWWWWWWWWWWWWWWWWW#=@WWW@==#WWWWWWWWWWWWWWW#==@WWWWW ║
echo ║ WWWWWWWWWWWWWWWWWWWWWWWWW#=@W#==#WWWWWWWWWWWWWWWWWWWWWWWWWW ║
echo ║ WWWWWWWWWWWWWWWWWWWWWWWWW=====@WWWWWWWWWWWWWWWWWWWWWWWWWWWW ║
echo ║ WWWWWWWWWWWWWWWWWWWWWWWWW====@WWWWWWWWWWWWWWWWWWWWWWWWWWWWW ║
echo ╚═════════════════════════════════════════════════════════════╝
echo - To start the server write npm start
@echo on
